// Code generated by Slice Machine. DO NOT EDIT.

import ImageBlock from './ImageBlock';
import ImagesWithText from './ImagesWithText';
import TextBlock from './TextBlock';
import VideoWithDescription from './VideoWithDescription';

export {
	ImageBlock,
	ImagesWithText,
	TextBlock,
	VideoWithDescription,
};

export const components = {
	image_block: ImageBlock,
	images_with_text: ImagesWithText,
	text_block: TextBlock,
	video_with_description: VideoWithDescription,
};
