// Code generated by Slice Machine. DO NOT EDIT.

import CalloutWithImage from './CalloutWithImage';
import Descriptions from './Descriptions';
import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	CalloutWithImage,
	Descriptions,
	HeroSlice,
	ImageGrid,
};

export const components = {
	callout_with_image: CalloutWithImage,
	descriptions: Descriptions,
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
};
